version: '3.8'

services:
  app:
    build: ""
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=/usr/src/app/data/pr_monitoring.sqlite
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build: ""
    command: node worker.js
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=/usr/src/app/data/pr_monitoring.sqlite
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
